### PR TITLE
Fix typo 'Failed to update package dependencies'

### PR DESCRIPTION
**Pull request by stevencl**
Original message was 'Failed to update package depencencies'

### CODE REVIEW

**Comment by mnquintana** [comment]
The spec is failing right now because it's expecting the message to match the typo – would you mind updating that?

**Comment by stevencl** [comment]
Sorry about that, I just submitted another pull request with a fix in the spec. Hopefully that works ok?

**Comment by mnquintana** [comment]
Actually, if it's not too much trouble would you mind updating it on the same branch? (You can just look for `patch-1` on your fork on GitHub and update it there.) It's just a bit easier to manage all in one PR. Thanks!

**Comment by mnquintana** [comment]
Thanks for this! :ship:

**Comment by stevencl** [comment]
Sorry about the hassle...

**Pull request merged**
